### ISSUE TITLE
Adapt riboviz to a new dataset

### ISSUE THREAD

**Issue by ewallace** [riboviz/workshop-2021-07-02#2]
Slides for adapting to a new dataset.

Introduce example datasets and give some examples.

Point out difficulties are most likely in config file at:

* adapters
* UMIs
* count_threshold
* annotation files

**Comment by ewallace** [comment]
This was started also in branch `overview-1`, indeed in the same slide presentation.

Needs:

* [ ] example-datasets screenshot
* [ ] Picture of transcriptome vs ORFeome
* [ ] Extended with `check_gff_fasta.py` concepts
* [ ] Picture of read structure - check with @acope3  and @john-s-f, who had some in their presentation?

**Comment by acope3** [comment]
@ewallace I'll send you a link to our presentation on Google Drive. Feel free to use any images you think could be useful.
